# Generated by Django 6.0.3 on 2026-03-11 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_produtos_estoque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoques',
            name='produto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estoque', to='core.produtos'),
        ),
    ]
